### ISSUE TITLE
Add a schema for source data files

### ISSUE THREAD

**Issue by JesseCrocker** [trailbehind/OpenHuntingData#16]
There needs to be a schema for source data files(files in /sources/), that defines what information goes in the source file.

This schema describes the input data. There will be another schema that describes the output data. see #3 for info on that.

Once this is complete data collection can be started.

The schema can later be used to auto-generate forms for creating source files, and can be used to validate source files before processing.

Json schema spec: http://json-schema.org/
Python module for validating json schema: https://pypi.python.org/pypi/jsonschema

**Comment by JesseCrocker** [comment]
A good start for creating this schema would be to take one of the existing source files, and write a schema that describes it. https://github.com/trailbehind/OpenHuntingData/blob/master/sources/US/MT/antelope.json

**Comment by slusset** [comment]
I'm looking at the schema branch and there is a schema.json file.  I've added some attributes along with a test script and test json file.  Not really crazy about leaving files at the root directory so I'll be looking into python project structure best practices and build systems.  Also, I can't push to the schema branch.  Do I need to create my own branch and then submit a PR from that branch -> schema or that branch -> master?

**Comment by JesseCrocker** [comment]
We generally use the git flow branching model. see https://guides.github.com/introduction/flow/ for more on that.

Basically: You should create  a fork, and then create a branch in your fork, then submit a pull request to master from there. If your fork is for a feature, start the name with feature/ if it's a bugfix then bugfix/

**Comment by JesseCrocker** [comment]
Source code can go in the scripts/ directory

**Comment by slusset** [comment]
I've got my local feature branch created, put I can't push.  Is there something that needs to happen to give me access to push to the remote repo?  Right now I get a 403.

**Comment by JesseCrocker** [comment]
You can't push to this repository. You need to create a fork and push to that.

**Comment by JesseCrocker** [comment]
There are going to end up being 2 schema files, for orginization purposes it seems like they should be in a directory, maybe schemas/.  so this will be schema/source.json  and later there will be a schemas/result.json
