### ISSUE TITLE
Create records for initial data

### ISSUE THREAD

**Issue by JesseCrocker** [trailbehind/OpenHuntingData#2]
# Montana

http://fwp.mt.gov/doingBusiness/reference/gisData/dataDownload.html
* only collect rows that start with “Hunting Districts - (2014 and 2015 Seasons)”

# Colorado

gather files from here: https://gisftp02.state.co.us/ (FYI, found via [searching here](http://www.arcgis.com/home/search.html?q=colorado%20parks%20and%20wildlife&t=groups&focus=groups))
 * collect cStateLevelAgenices/DNR/CPW/From/2015/GISData/AdministrativeData/CPW_GMUBoundaries.zip

**Comment by michi-mur** [comment]
completed in PR #11 and PR #13.
